version: "3.9"
services:
  artwork:
    container_name: artwork
    build:
      context: microservices/artwork
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/artwork:/artwork
      - /artwork/node_modules

  certificate:
    container_name: certificate
    build:
      context: microservices/certificate
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/certificate:/certificate
      - /certificate/node_modules

  identity:
    container_name: identity
    build:
      context: microservices/identity
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./microservices/identity:/identity
      - /identity/node_modules

  order:
    container_name: order
    build:
      context: microservices/order
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./microservices/order:/order
      - /order/node_modules

  payment:
    container_name: payment
    build:
      context: microservices/payment
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./microservices/payment:/payment
      - /payment/node_modules

  frontend:
    container_name: frontend
    build:
      context: microservices/frontend
      dockerfile: Dockerfile
    volumes:
      - ./microservices/frontend:/frontend
      - ./microservices/frontend/config/nginx-frontend.conf:/etc/nginx/conf.d/nginx-frontend.conf
      - /frontend/node_modules

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: artwork123
      MONGO_INITDB_DATABASE: artwork

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  gateway:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx/nginx-gateway.conf:/etc/nginx/conf.d/nginx-gateway.conf
    depends_on:
      - mongo
      - redis
      - artwork
      - certificate
      - identity
      - order
      - payment
      - frontend

