name: CI Payment

on:
  push:
    paths:
      - 'microservices/payment/**'
    branches:
      - main
  pull_request:
    paths:
      - 'microservices/payment/**'
    branches:
      - main

env:
  NAME: payment
  PORT: 3000
  SERVER_TIMEOUT: 20000
  DB_URI: ${{ secrets.PAYMENT_DB_URI }}
  SECRET: ${{ secrets.JWT_SECRET }}

defaults:
  run:
    working-directory: microservices/payment

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
              cache: 'npm'
              cache-dependency-path: ./microservices/payment/package-lock.json

          - run: npm ci
          - run: npm run lint

  test:
      name: Test
      runs-on: ubuntu-latest
      needs: lint
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
              cache: 'npm'
              cache-dependency-path: ./microservices/payment/package-lock.json

          - run: npm ci
          - run: npm test